keys:
  - &users:
    - &sumi 2C0E62B7117471A5
    - &sumi_mother age1w4dld6acqnhctzq32nhnajw0ewgkq7295k3ue3cgg0pwpt0re3asg4ajs3
    - &sumi_win-mother age1vzlm35vjkyhgedm7vtafz8xfl2zq3e69plp5w7t4uueyjhy4p5ysanplm2
    - &sumi_stacia age1znnqnxjkr0x70r5ys0n2k34ym5a3spn69yuveqa76wh0ng65catspphysl
    - &sumi_zephyrus age1svkysj8mj8u2k9cag4l0pthf7t3e8jn2jy0ygacper8f349k299q03nn9t
    - &kobayashi_univ age1g4d4ftujlypmh8z0g3s6w9k9kjjd4lped3k5egvxnzhyelp8945qzg35fn
    - &work_laptop age12lsvwdrtnllmlxffy9077l7kjj85vz8sjkjl3nknfncaqpyqm9rq48urgf
    - &work_server age1ppxdp9wsxpg8yr0a2wsc982x2ua22meh72kae0l2xln95px4jyxq90kuel
  - &desktops:
    - &mother age1dx0hn7ug2nfd9sxw0q3hvegh8llqt0084x7gzk20s20lptrujs6sv48akw
    - &stacia age12994fjtztfkz06rtg0w6gxrzne3z0y223zumu293jtdsfukukussq233na
    - &soleus age1qz3tcqfgaxhhq2nemjc9x4wq2je47a9m3840xwxy0a979c8vh3gsj7w2yf
    - &zephyrus age1lc2dnrqr84rat2aqmm9g78mssuxm40vsswr7lnaz59n97qjgg9csx2wekj
creation_rules:
  - path_regex: sops/hosts/mother/secrets.yaml
    key_groups:
      - pgp:
          - *sumi
        age:
          - *mother
  - path_regex: sops/hosts/stacia/secrets.yaml
    key_groups:
      - pgp:
          - *sumi
        age:
          - *stacia
  - path_regex: sops/hosts/soleus/*
    key_groups:
      - pgp:
          - *sumi
        age:
          - *soleus
  - path_regex: sops/hosts/zephyrus/secrets.yaml
    key_groups:
      - pgp:
          - *sumi
        age:
          - *zephyrus
  - path_regex: sops/system/network/wireless
    key_groups:
      - pgp:
          - *sumi
        age:
          - *zephyrus
  - path_regex: sops/system/openfortivpn/config
    key_groups:
      - pgp:
          - *sumi
        age:
          - *mother
          - *zephyrus
  - path_regex: sops/pkgs/ssh/desktops$
    key_groups:
      - pgp:
          - *sumi
        age:
          - *sumi_mother
          - *sumi_win-mother
          - *sumi_zephyrus
  - path_regex: sops/pkgs/ssh/servers$
    key_groups:
      - pgp:
          - *sumi
        age:
          - *sumi_mother
          - *sumi_zephyrus
  - path_regex: sops/pkgs/ssh/univ$
    key_groups:
      - pgp:
          - *sumi
        age:
          - *sumi_mother
          - *sumi_stacia
          - *sumi_zephyrus
          - *kobayashi_univ
  - path_regex: sops/pkgs/ssh/work$
    key_groups:
      - pgp:
          - *sumi
        age:
          - *work_laptop
  - path_regex: sops/pkgs/[aichat,codecompanion]/*
    key_groups:
      - pgp:
          - *sumi
        age:
          - *sumi_mother
          - *sumi_stacia
          - *sumi_zephyrus
          - *kobayashi_univ
  - path_regex: sops/pkgs/wezterm/[^/]+\.lua$
    key_groups:
      - pgp:
          - *sumi
        age:
          - *sumi_mother
          - *sumi_stacia
          - *sumi_zephyrus
  - path_regex: sops/users/work/secrets.yaml$
    key_groups:
      - pgp:
          - *sumi
        age:
          - *work_server
