[default]
[default.extend-words]
hda = "hda"
HD = "HD"
tre = "tre"

[files]
extend-exclude = [
    "sops/**",
    "flake.lock",
    "CHANGELOG.md",
    "chezmoi/.chezmoidata/**",
    "apps/user/cli/develop/ranger/default.nix",
    "apps/user/cli/develop/ranger/config/*",
    "apps/user/desktop/env/core/ime/skk/fcitx5/**",
    "apps/user/desktop/env/core/ime/skk/libskk/**",
]
