[linux.system.env.PATH]
[linux.system.env.export]
XDG_CACHE_HOME = "$HOME/.cache"
XDG_CONFIG_HOME = "$HOME/.config"
XDG_DATA_HOME = "$HOME/.local/share"
XDG_DESKTOP_DIR = "$HOME/Desktop"
XDG_DOCUMENTS_DIR = "$HOME/Documents"
XDG_DOWNLOAD_DIR = "$HOME/Downloads"
XDG_GAME_DIR = "$HOME/Game"
XDG_MUSIC_DIR = "$HOME/Music"
XDG_PICTURES_DIR = "$HOME/Pictures"
XDG_PUBLICSHARE_DIR = "$HOME/Public"
XDG_STATE_HOME = "$HOME/.local/state"
XDG_TEMPLATES_DIR = "$HOME/Templates"
XDG_VIDEOS_DIR = "$HOME/Videos"
XDG_WORKSPACE_DIR = "$HOME/workspace"

[linux.system.env.alias]
egrep = "grep -E --color=auto"
fgrep = "grep -F --color=auto"
grep = "grep --color=auto"
ls = "ls --color=auto"
