[windows.system.env]
PATH = []
[windows.system.env.export]

[windows.system.registers]
[windows.system.registers."HKLM:\\SYSTEM\\CurrentControlSet\\Control\\FileSystem"]
name = "LongPathsEnabled"
value = 1
[windows.system.registers."HKCU:\\Control Panel\\Desktop"]
name = "PaintDesktopVersion"
value = 1

[windows.system.defender]
exclution_paths = [
    "$env:USERPROFILE\\.cache",
    "$env:USERPROFILE\\.config",
    "$env:USERPROFILE\\.dotfiles",
    "$env:USERPROFILE\\.local\\share",
    "$env:USERPROFILE\\.local\\state",
    "$env:USERPROFILE\\bin",
    "$env:USERPROFILE\\scoop",
    "$env:USERPROFILE\\src",
    "$env:USERPROFILE\\pkg",
    "$env:USERPROFILE\\Hyper-V",
    "$env:USERPROFILE\\VirtualBox VMs",
    "$env:ProgramData\\scoop",
]

[windows.system.optional_features]
enabled = [
    "Containers",
    "Microsoft-Hyper-V",
    "Microsoft-Windows-Subsystem-Linux",
    "HypervisorPlatform",
    "VirtualMachinePlatform",
]
disabled = ["WorkFolders-Client"]

[windows.system.debloat]
options = [
    "-Silent",
    "-ClearStart",
    "-DisableBing",
    "-DisableDVR",
    "-DisableLockscreenTips",
    "-DisableRecall",
    "-DisableSuggestions",
    "-DisableTelemetry",
    "-DisableWidgets",
    "-HideChat",
    "-HideSearchTb",
    "-RemoveAppsCustom",
    "-ShowHiddenFolders",
    "-ShowKnownFileExt",
    "-ShowSearchIconTb",
]
remove_apps = [
    ### "Microsoft Apps",
    "Clipchamp.Clipchamp",
    "Microsoft.3DBuilder",
    "Microsoft.549981C3F5F10 #Cortana app",
    "Microsoft.BingFinance",
    "Microsoft.BingFoodAndDrink",
    "Microsoft.BingHealthAndFitness",
    "Microsoft.BingNews",
    "Microsoft.BingSports",
    "Microsoft.BingTranslator",
    "Microsoft.BingTravel",
    "Microsoft.BingWeather",
    "Microsoft.Getstarted # Cannot be uninstalled in Windows 11",
    "Microsoft.Messaging",
    "Microsoft.Microsoft3DViewer",
    "Microsoft.MicrosoftJournal",
    # "Microsoft.MicrosoftOfficeHub",
    "Microsoft.MicrosoftPowerBIForWindows",
    "Microsoft.MicrosoftSolitaireCollection",
    "Microsoft.MicrosoftStickyNotes",
    "Microsoft.MixedReality.Portal",
    "Microsoft.NetworkSpeedTest",
    "Microsoft.News",
    "Microsoft.Office.OneNote",
    "Microsoft.Office.Sway",
    "Microsoft.OneConnect",
    "Microsoft.Print3D",
    "Microsoft.SkypeApp",
    "Microsoft.Todos",
    # "Microsoft.WindowsAlarms",
    "Microsoft.WindowsFeedbackHub",
    "Microsoft.WindowsMaps",
    # "Microsoft.WindowsSoundRecorder",
    "Microsoft.XboxApp # Old Xbox Console Companion App, no longer supported",
    "Microsoft.ZuneVideo",
    "MicrosoftCorporationII.MicrosoftFamily # Family Safety App",
    "MicrosoftCorporationII.QuickAssist",
    "MicrosoftTeams # Old MS Teams personal (MS Store)",
    "MSTeams # New MS Teams app",
    ### "Third Party Apps",
    "ACGMediaPlayer",
    "ActiproSoftwareLLC",
    "AdobeSystemsIncorporated.AdobePhotoshopExpress",
    "Amazon.com.Amazon",
    "AmazonVideo.PrimeVideo",
    "Asphalt8Airborne",
    "AutodeskSketchBook",
    "CaesarsSlotsFreeCasino",
    "COOKINGFEVER",
    "CyberLinkMediaSuiteEssentials",
    "DisneyMagicKingdoms",
    "Disney",
    "DrawboardPDF",
    "Duolingo-LearnLanguagesforFree",
    "EclipseManager",
    "Facebook",
    "FarmVille2CountryEscape",
    "fitbit",
    "Flipboard",
    "HiddenCity",
    "HULULLC.HULUPLUS",
    "iHeartRadio",
    "Instagram",
    "king.com.BubbleWitch3Saga",
    "king.com.CandyCrushSaga",
    "king.com.CandyCrushSodaSaga",
    "LinkedInforWindows",
    "MarchofEmpires",
    "Netflix",
    "NYTCrossword",
    "OneCalendar",
    "PandoraMediaInc",
    "PhototasticCollage",
    "PicsArt-PhotoStudio",
    "Plex",
    "PolarrPhotoEditorAcademicEdition",
    "Royal Revolt",
    "Shazam",
    "Sidia.LiveWallpaper",
    "SlingTV",
    "Spotify",
    "TikTok",
    "TuneInRadio",
    "Twitter",
    "Viber",
    "WinZipUniversal",
    "Wunderlist",
    "XING",
    "Microsoft.BingSearch # Web Search from Microsoft Bing (Integrates into Windows Search)",
    "Microsoft.Copilot # New Windows Copilot app",
    # "Microsoft.Edge                         # Edge browser (Can only be uninstalled in European Economic Area)",
    # "Microsoft.GetHelp # Required for some Windows 11 Troubleshooters",
    "Microsoft.MSPaint # Paint 3D",
    "Microsoft.OneDrive # OneDrive consumer",
    "Microsoft.Paint # Classic Paint",
    "Microsoft.ScreenSketch # Snipping Tool",
    "Microsoft.Whiteboard # Only preinstalled on devices with touchscreen and/or pen support",
    # "Microsoft.Windows.Photos",
    # "Microsoft.WindowsCalculator",
    # "Microsoft.WindowsCamera",
    # "Microsoft.WindowsNotepad",
    # "Microsoft.WindowsStore # Microsoft Store, WARNING: This app cannot be reinstalled!",
    # "Microsoft.WindowsTerminal # New default terminal app in windows 11",
    # "Microsoft.Xbox.TCUI                    # UI framework, seems to be required for MS store, photos and certain games",
    # "Microsoft.XboxIdentityProvider         # Xbox sign-in framework, required for some games",
    # "Microsoft.XboxSpeechToTextOverlay      # Might be required for some games, WARNING: This app cannot be reinstalled!",
    "Microsoft.YourPhone # Phone link",
    "Microsoft.ZuneMusic # Modern Media Player",
    "MicrosoftWindows.CrossDevice # Phone integration within File Explorer, Camera and more",
    "Microsoft.GamingApp # Modern Xbox Gaming App, required for installing some PC games",
    "Microsoft.OutlookForWindows # New mail app: Outlook for Windows",
    "Microsoft.People # Required for & included with Mail & Calendar",
    # "Microsoft.PowerAutomateDesktop",
    # "Microsoft.RemoteDesktop",
    "Microsoft.Windows.DevHome",
    "Microsoft.windowscommunicationsapps # Mail & Calendar",
    # "Microsoft.XboxGameOverlay # Game overlay, required/useful for some games",
    # "Microsoft.XboxGamingOverlay # Game overlay, required/useful for some games",
]
