[apps.users.sumi]
[apps.users.sumi.git]
userEmail = "sumiharu@misumi-sumi.com"
userName = "misumisumi"
signingKey = "F9C2261B92168D38"
paper = "delta"
diffFilter = "delta"

[apps.users.sumi.lazygit]
paper = "delta --dark --paging=never"

[apps.users.sumi.shell]
historyIgnore = [
    "builtin cd *",
    "cd *",
    "history *",
    "kill *",
    "ls *",
    "mkdir *",
    "pkill *",
    "rm *",
]

[apps.users.sumi.bash]
bashrcExtra = ""
initExtra = ""
logoutExtra = ""
profileExtra = ""
[apps.users.sumi.bash.sessionVariables]

[apps.users.sumi.zsh]
extraFunctions = ["zargs", "zmv", "zcp", "zln"]
extraModules = ["attr"]
extraOptions = [
    "EXTENDED_GLOB",     # 拡張GRUBの有効化(^: 否定、~: 除外)
    "BARE_GLOB_QUAL",    # 条件付け検索の有効化
    "MAGIC_EQUAL_SUBST", # cmd a=/to/pathの時に補完を効かせる
]

envExtra = '''
# Compatibilize with bash
export HOSTNAME=$(hostname)
'''
initExtraFirst = '''
# Calc startup time
# zmodload zsh/zprof
# zprof
'''
initExtraBeforeCompInit = ""
initExtra = '''
# The plugin will auto execute this zvm_after_init function
setopt EXTENDED_GLOB         # 拡張GRUBの有効化(^: 否定、~: 除外)
setopt BARE_GLOB_QUAL        # 条件付け検索の有効化
setopt MAGIC_EQUAL_SUBST     # cmd a=/to/pathの時に補完を効かせる

set vi-cmd-mode-string "\1\e[?8c\2"
set vi-ins-mode-string "\1\e[?0c\2"
# For marlonrichert/zsh-autocomplete
zstyle -e ':autocomplete:history-search-backward:*' list-lines 'reply=$(( LINES / 2 ))'
zstyle ':autocomplete:*' min-delay 0.05
zstyle ':completion:*' completer \
    _complete _complete:-fuzzy _correct _approximate _ignored
bindkey '\t' menu-select "$terminfo[kcbt]" menu-select
bindkey -M menuselect '\t' menu-complete "$terminfo[kcbt]" reverse-menu-complete
'''
[apps.users.sumi.zsh.localVariables]
ZVM_VI_INSERT_ESCAPE_BINDKEY = "jj"
ZVM_VI_VISUAL_ESCAPE_BINDKEY = "jj"
ZVM_VI_OPPEND_ESCAPE_BINDKEY = "jj"
ZVM_LINE_INIT_MODE = "$ZVM_MODE_INSERT"
ZVM_LAZY_KEYBINDINGS = false
ABBR_QUIET = 1

[apps.users.sumi.zsh.zinit]
[apps.users.sumi.zsh.zinit.plugins]
"lucid blockf depth=1 light-mode" = [
    "atload'zvm_init' jeffreytse/zsh-vi-mode",
    "zsh-users/zsh-autosuggestions",
    "marlonrichert/zsh-autocomplete",
]
"wait'0b' lucid nocd depth=1 light-mode" = ["olets/zsh-abbr"]
"wait'!1a' lucid blockf depth=1 light-mode" = [
    "zdharma-continuum/fast-syntax-highlighting",
]
"wait'1b' lucid depth=1 light-mode" = ["hlissner/zsh-autopair"]
[apps.users.sumi.zsh.zinit.prezto]
pmodules = ["environment", "terminal"]
[apps.users.sumi.zsh.zinit.prezto.pmodulesWithModifier]
"wait'0a' lucid" = ["directory", "spectrum"]
