[apps.users.kobayashi.git]
userEmail = "sumiharu@misumi-sumi.com"
userName = "misumisumi"
signingKey = "F9C2261B92168D38"
paper = "$env:USERPROFILE\\scoop\\shims\\delta"
diffFilter = "$env:USERPROFILE\\scoop\\shims\\delta"

[apps.users.kobayashi.lazygit]
paper = "$env:USERPROFILE\\scoop\\shims\\delta --dark --paging=never"

####################################################################################################
# For linux
####################################################################################################
[linux.users.sumi]
externals = ["blesh", "tpm"]
[linux.users.kobayashi.sops]

[linux.users.kobayashi.env.PATH]
[linux.users.kobayashi.env.export]
EDITOR = "nvim"
FZF_ALT_C_COMMAND = "fd --type d"
FZF_ALT_C_OPTS = "--preview 'tree -C {} | tree -200'"
FZF_CTRL_R_OPTS = "--preview 'echo {}' --preview-window up:3:hidden:wrap --bind 'ctrl-/:toggle-preview' --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort' --color header:italic --header 'Press CTRL-Y to copy command into clipboard'"
FZF_CTRL_T_COMMAND = "fd --type f"
FZF_CTRL_T_OPTS = "--preview 'bat -n --color: always {}' --bind 'ctrl-/:change-preview-window(down|hidden|)'"
FZF_TMUX = "1"
FZF_TMUX_OPTS = "-p -w 80% -h 70%"
JQ_COLORS = "1;30:0;37:0;37:0;37:0;32:1;37:1;37"
LG_CONFIG_FILE = "/home/$(whoami)/.config/lazygit/config.yml"
MANPAGER = "sh -c 'sed -u -e \\\"s%\\\\x1B\\[[0-9;]*m%%g; s%.\\\\x08%%g\\\" | bat -p -lman'"
TMUX_TMPDIR = "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
LD_LIBRARY_PATH = "find /disk/fs1/soft/cuda/cuda-* -maxdepth 1 -name \"lib64\" -exec printf \"%s:\" {} + | sed 's/:$//'"
CUDA_HOME = "/disk/fs1/soft/cuda/cuda-12.4.1_cudnn-9.2.0.82/lib64"
[linux.users.kobayashi.env.alias]

[linux.users.kobayashi.packages.mise.settings]
idiomatic_version_file = true
always_keep_download = false
always_keep_install = false
plugin_autoupdate_last_check_duration = "1 week"
verbose = false
http_timeout = "30s"
jobs = 4
raw = false
yes = false
not_found_auto_install = true
auto_install = true
experimental = true

[linux.users.kobayashi.packages.mise.tools]
bat = "latest"
btop = "latest"
cmake = "latest"
delta = "latest"
deno = "latest"
duf = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
github-cli = "latest"
go = "latest"
imagemagick = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
nodejs = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
tree-sitter = "latest"
uv = "latest"
yazi = "latest"
yt-dlp = "latest"
zoxide = "latest"
