{
	"data": "ENC[AES256_GCM,data:8XDPNAECDqkK2vdCmDHPyS9Y0Sd0i2F/8Msxn1OpMZ0N4GDlbtpyJpHCmQndCwtzO8T7qWLTLKFZGi/k7qckutqNjov61Cpt08BkXR3cKqrDwACoSU1k/U39/Atba1wAvNXYLjmL2vSdP0k/Eq/NkaJehmNH,iv:n9y77GREy7RMdf7zdhqTs7M4hZ6wffiq+Thu5Fl8/Cs=,tag:cR0/oZCDj8MOuhPELLo+KQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1w4dld6acqnhctzq32nhnajw0ewgkq7295k3ue3cgg0pwpt0re3asg4ajs3",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RUdScGNZbzAwMTFmQWZn\nclJ0MkNBamoybUVJdCtlaFlmcEE5VzZEaUNzClIxYnBKY2NDczAwbGk0WFBOS2hk\nNTR4WjhEc2JSUjR1VlhXRVBJVGEvT0kKLS0tIHFtMmQ3T3FyM2llSlRPSzhCQjkv\ncXZCL21GUHlveXVhcXA3ckYrNGRlZzgKVT3+MtaHpqpCNatS+kcRDqAEtkZma5Ek\nmEndK6ynUrARlEFbQkk4rO7euD3/Xb6x/AMid3J2sDstMG6Wf3xmsA==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1znnqnxjkr0x70r5ys0n2k34ym5a3spn69yuveqa76wh0ng65catspphysl",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYzRpSDZUSWRITHRSMkxJ\nb1J1a0pxV01ZcHltSy8rNndmekh1LzhXQkcwCmVWSzBtc3VwTFJMZ0pTUjloRlF3\nZUhvVUlVUVl0YWtmbFF3WlJLbHV6QmMKLS0tIHhCZ013Vy9Hb2U5TXFkR2Fpcldl\nWXJsOU5tTjUzQmF0Rm9vcG1yZXJOWDQKBzKVXcdDgoeVhdZCUWQ+ht34mQvzFSKU\nkmxtIL87D6D/DKLAmZQzCas77fsToYuSGcmF8aapHezxUy1Vc79XXg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1qggvd6rfs83grgl5u05cythrtc8ny2dkq9ad53lsfekmg2fk7dfqgnt6p5",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSndIWEdaMkZsNittS08z\naHpTQ2RLNWdhSUFkWlVkTmhXQ1dBLzBZMnlRCjJJelA4UFloZERZcG03T0IxNmh4\nSm1lbEJ5NFl0cE92eGpNTnE2UlVISzQKLS0tIGVKRHVBcXZ3enkvL0krSWUvdDVo\nNUdEMjlzQVVsd2kvK3FMQkdFczZvRGMKme3M22p9NG+EUMmvEGW0IZCQgAXrq7RH\nNIZjlwZ543KEtl3qqmyNgZI8ZykSo3isJYZw2ukbfLURrmzmJ1+5kw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-04-28T04:06:56Z",
		"mac": "ENC[AES256_GCM,data:BNyRefk7Fiq2H7RvxXAlrlWlQrbE/xRfSdlOYOz3wEA+HpN2mR4aKBUb+QuDVB225qRcLqZ2h0ZLbM+felX7A/lIvUZVluPjnncmfOCIntZdPRKt/+UJyhWYBjvt6DFVpzSH/T1ogD6yb/qX+mhYw3a0VTQfDcIoDZ06q+FmyHQ=,iv:Yzzudcr+VtxtJGVegD5nQR3bSd/RZkKb44rCMwKVdoY=,tag:k/WBEOHDSREcgipkqfrdTQ==,type:str]",
		"pgp": [
			{
				"created_at": "2025-04-28T04:06:56Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhF4DAAAAAAAAAAASAQdA+SQ+uqWbfC/MxME3vM5/a5LU7VRCrxx18CVrCZY71WEw\nVIXcJptCnoHfVprEH5xBXTn/FBmElHld/ieXC50ImoXqyFH5LfBHKNj4HCjuRaiY\n0l4B4NGPyqEKpRTiCo2RAFCn8pKd9qtXDNWiLSx4ZwtlC3nz9o86kXQEGGZ2wBpW\nYLbWibyLjPszIRfoRdLhdd+faWXJBOOcpZmTyr36Ao/ZVUt8I/KNrjGXulS1VJMx\n=w8wd\n-----END PGP MESSAGE-----",
				"fp": "2C0E62B7117471A5"
			}
		],
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.1"
	}
}
