# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot = {
    initrd = {
      availableKernelModules = [
        "ahci"
        "nvme"
        "xhci_pci"
        "usbhid"
        "usb_storage"
        "uas"
        "sr_mod"
        "sd_mod"
      ];
      kernelModules = [ "dm-snapshot" ];
    };
  };
}
