[container]
format = '[$symbol \[$name\]]($style) '
style = "fg:fg bg:terminal_dark"

[hostname]
ssh_only = true
format = '[$ssh_symbol$hostname ]($style)'
style = "fg:magenta bg:terminal_dark"
ssh_symbol = " "

[username]
style_root = "fg:magenta bg:terminal_dark"
style_user = "fg:fg bg:terminal_dark"
format = "[ $user/]($style)"
show_always = false

[cmd_duration]
min_time = 2000
style = "fg:fg bg:terminal_dark"
format = "[ 󱦟 took $duration ]($style)"

[git_branch]
symbol = " "
style = "fg:cyan bg:terminal_dark"
format = '[ $symbol$branch ]($style)'

[git_metrics]
added_style = "fg:cyan bg:terminal_dark"
deleted_style = "fg:red bg:terminal_dark"
format = "([+$added ]($added_style))([-$deleted]($deleted_style) )"
disabled = false

[git_status]
style = "bg:terminal_dark"
ahead = '⇡${count}'
behind = '⇣${count}'
conflicted = "=${count}"
deleted = "✘${count}"
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
modified = "!${count}"
renamed = "»${count}"
staged = "+${count}"
stashed = '\$$count'
untracked = "?${count}"
format = '[[($all_status$ahead_behind )](fg:yellow bg:terminal_dark)]($style)'
windows_starship = '/mnt/c/Users/username/scoop/apps/starship/current/starship.exe'

[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = "bg:#1d2230"
format = '[  $time ]($style)'

[aws]
symbol = "  "
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[azure]
disabled = true
format = '[$symbol($subscription)]($style) '
symbol = 'ﴃ '
style = "fg:fg bg:terminal_dark"

[buf]
symbol = " "
style = "fg:fg bg:terminal_dark"

[c]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[conda]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[dart]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[directory]
read_only = " "
read_only_style = "fg:magenta bg:terminal_dark"
style = "fg:cyan bg:terminal_dark"
format = '[  $path]($style)[$read_only ]($read_only_style)'
truncation_length = 0
truncate_to_repo = false
truncation_symbol = "…/"

[docker_context]
symbol = " "

[elixir]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[elm]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[fossil_branch]
symbol = " "
style = "fg:fg bg:terminal_dark"
format = '[$symbol$branch]($style)'

[golang]
symbol = "ﳑ"
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[guix_shell]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[haskell]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[haxe]
symbol = "⌘ "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[hg_branch]
symbol = " "
style = "fg:fg bg:terminal_dark"
format = '[$symbol$branch(:$topic) ]($style)'

[java]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[julia]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[lua]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "⬢ "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[nim]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[nix_shell]
symbol = " "
style = "bg:terminal_dark"
heuristic = true
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[nodejs]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[os]
style = "fg:fg bg:terminal_dark"
disabled = false

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = "󰂹 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = "󰏗 "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[pijul_channel]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[php]
symbol = ""
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[python]
symbol = " "
style = "fg:fg bg:terminal_dark"
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'

[rlang]
symbol = "ﳒ "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[ruby]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[rust]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[scala]
symbol = " "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[spack]
symbol = "🅢 "
style = "bg:terminal_dark"
format = '[[ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'
