[".local/bin/fd"]
type = "archive-file"
url = "https://github.com/sharkdp/fd/releases/download/{{ (gitHubLatestRelease 'sharkdp/fd').TagName }}/fd-{{ (gitHubLatestRelease 'sharkdp/fd').TagName }}-{{ .chezmoi.arch }}-{{ if -eq .chezmoi.os 'windows' }}pc-windows-msvc.zip{{ else if -eq .chezmoi.os 'darwin' }}apple-darwin.tar.gz{{ else }}unknown-linux-musl.tar.gz{{ end }}"
path = "fd-{{ (gitHubLatestRelease 'sharkdp/fd').TagName }}-{{ .chezmoi.arch }}-{{ if -eq .chezmoi.os 'windows' }}pc-windows-msvc{{ else if -eq .chezmoi.os 'darwin' }}apple-darwin{{ else }}unknown-linux-musl{{ end }}/fd"
executable = true
readonly = true
refreshPeriod = "168h"

#TODO: extracting completion
