[".local/bin/zoxide"]
type = "archive-file"
url = "https://github.com/ajeetdsouza/zoxide/releases/download/{{ (gitHubLatestRelease 'ajeetdsouza/zoxide').TagName }}/zoxide-{{ (gitHubLatestRelease 'ajeetdsouza/zoxide').TagName }}-{{ .chezmoi.arch }} -{{ if -eq .chezmoi.os 'windows' }}pc-windows-msvc.zip{{ else if -eq .chezmoi.os 'darwin' }}apple-darwin.tar.gz{{ else }}unknown-linux-musl.tar.gz{{ end }}"
path = "zoxide-{{ (gitHubLatestRelease 'ajeetdsouza/zoxide').TagName }}-{{ .chezmoi.arch }} -{{ if -eq .chezmoi.os 'windows' }}pc-windows-msvc{{ else if -eq .chezmoi.os 'darwin' }}apple-darwin{{ else }}unknown-linux-musl{{ end }}/zoxide"
executable = true
readonly = true
refreshPeriod = "168h"

#TODO: extracting completion
