name: approve and merge instead of me
on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: string
      triggered-name:
        required: true
        type: string
    secrets:
      AGENT_OF_ME_APP_ID:
        required: true
      AGENT_OF_ME_PRIVATE_KEY:
        required: true

jobs:
  workflow-status:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'misumisumi'
    outputs:
      all-success: ${{ steps.workflow-status.outputs.all-success }}
      existing-review: ${{ steps.workflow-status.outputs.existing-review }}
      pr-author-id: ${{ steps.workflow-status.outputs.pr-author-id }}
    steps:
      - name: Check workflow status
        id: workflow-status
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          PR_NUM: ${{ inputs.pr-number }}
        run: |
          # no check agent-of-me workflow
          check_all_success=$(gh pr view "${PR_NUM}" --json statusCheckRollup --jq '[.[].[] | select(.name | test("workflow") | not) | .conclusion] | map(if . == "" then "-" else . end) | all(. == "SUCCESS" or . == "NEUTRAL")')
          existing_review=$(gh pr view "${PR_NUM}" --json reviews --jq '.reviews | length > 0')
          pr_author_id=$(gh pr view "${PR_NUM}" --json author --jq '.author.id')
          cat <<EOF >> "$GITHUB_OUTPUT"
          existing-review=${existing_review}
          all-success=${check_all_success}
          pr-author-id=${pr_author_id}
          EOF

  # INFO: https://github.com/cli/cli/issues/2342
  dismiss-reviews:
    runs-on: ubuntu-latest
    needs: workflow-status
    if: >-
      ${{
        contains(fromJSON('["misumisumi", "[bot]"]'), github.actor) &&
        inputs.triggered-name == 'build check' &&
        needs.workflow-status.outputs.existing-review == 'true' &&
        needs.workflow-status.outputs.all-success == 'false'
       }}
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.AGENT_OF_ME_APP_ID }}
          private_key: ${{ secrets.AGENT_OF_ME_PRIVATE_KEY }}

      - name: Dismiss approvals
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh api repos/${{ github.repository }}/pulls/${{ inputs.pr-number }}/reviews \
            --jq '.[] | select(.state == "APPROVED") | .id' \
            | xargs -I '{}' gh api --method=PUT -f message="Dismissed due to PR edit." \
            repos/${{ github.repository }}/pulls/${{ inputs.pr-number }}/reviews/'{}'/dismissals

  approve-owner:
    runs-on: ubuntu-latest
    needs: workflow-status
    if: >-
      ${{
        needs.workflow-status.outputs.pr-author-id == 'MDQ6VXNlcjI0NDUxOTc4' &&
        needs.workflow-status.outputs.all-success == 'true'
       }}
    env:
      GH_REPO: ${{ github.repository }}
      PR_NUM: ${{ inputs.pr-number }}
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.AGENT_OF_ME_APP_ID }}
          private_key: ${{ secrets.AGENT_OF_ME_PRIVATE_KEY }}

      - name: Auto approve
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh pr review --approve "${PR_NUM}"

  merge-pr-created-by-bot:
    runs-on: ubuntu-latest
    needs: workflow-status
    if: >-
      ${{
        github.actor == 'workflow-executor[bot]' &&
        needs.workflow-status.outputs.all-success == 'true'
      }}
    env:
      GH_REPO: ${{ github.repository }}
      PR_NUM: ${{ inputs.pr-number }}
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.AGENT_OF_ME_APP_ID }}
          private_key: ${{ secrets.AGENT_OF_ME_PRIVATE_KEY }}

      - name: Auto approve and merge for bot PRs
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh pr review --approve "$PR_NUM"
          gh pr merge --merge --auto "$PR_NUM"

  merge-pr-created-by-dependabot:
    runs-on: ubuntu-latest
    needs: workflow-status
    if: >-
      ${{
        github.actor == 'dependabot[bot]' &&
        needs.workflow-status.outputs.all-success == 'true'
      }}
    env:
      GH_REPO: ${{ github.repository }}
      PR_NUM: ${{ inputs.pr-number }}
    steps:
      - uses: dependabot/fetch-metadata@v2
        id: metadata
        with:
          github-token: ${{ github.token }}

      - name: Auto approve and merge for dependabot PRs
        if: contains(fromJSON('["minor", "patch"]'), steps.metadata.outputs.update-type)
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr review --approve "$PR_NUM"
          gh pr merge --merge --auto "$PR_NUM"
